"""add_scenario_segment_tables

Revision ID: 8df2d3f8096a
Revises: a682b7710052
Create Date: 2026-02-08 14:03:59.932079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df2d3f8096a'
down_revision: Union[str, None] = 'a682b7710052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=True)
    op.create_table('segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('generation_status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'sequence_number', name='uq_segment_scenario_seq')
    )
    op.create_index(op.f('ix_segments_scenario_id'), 'segments', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_scenario_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
